### ISSUE TITLE
NoMethodError: undefined method `scan' for {}:Hash

### ISSUE THREAD

**Issue by jerodsanto** [diogob/activerecord-postgres-hstore#113]
I'm on rails 4.0.0 and your master branch. When I try to create an object with an hstore attribute I get: 

```
NoMethodError: undefined method `scan' for {}:Hash`.
```

This is happening inside `PgHstore.load` when calling `scan` on the passed in default Hash that is sent to it from `ActiveRecord::Coders::Hstore#from_hstore`.

I believe `PgHstore.load` is expecting a string here, but the Hstore coder is sending it a hash. Is that an accurate assessment?

**Comment by tsov** [comment]
@prcongithub +1
Need a fix for this too

**Comment by diogob** [comment]
@tsov can you send a failing spec?

**Comment by tsov** [comment]
I am on Rails 3.2.11 using activerecord-postgres-hstore 0.7.7 and Identity Cache 0.7.7

When I `fetch` models from cache and try to call as_json on them I get the same error =>

```ruby
NoMethodError: undefined method `scan' for {}:Hash`.
```

problem is gone if I remove the line

```ruby
serialize :properties, ActiveRecord::Coders::Hstore
```

Found out you can use `store_accessor` instead, which also removes the error, but it does not serialize my property anymore :/

Need any more info?

**Comment by diogob** [comment]
@tsov I would like to have a failing spec, so it makes it easier for me to reproduce the error. You can send as a pull request.

**Comment by tsov** [comment]
Also when I have this line in my model

```ruby
serialize :properties, ActiveRecord::Coders::Hstore
```

and call 

```ruby
2.1.2 :005 > Content.fetch_by_id('28819')
(Object doesn't support #inspect)
 =>  
```

so it doesn't seem to be able to serialize the object anymore :/

**Comment by tsov** [comment]
Sure can do!
