### ISSUE TITLE
Rails 4.2 Error: undefined method `simplified_type'

### ISSUE THREAD

**Issue by chibicode** [diogob/activerecord-postgres-hstore#127]
Can't start Rails 4.2 with activerecord-postgres-hstore.

Echoing this thread:
https://github.com/rails/rails/issues/18111#issuecomment-67747838

Just FYI, `simplified_type` is removed on Rails 4.2:
https://github.com/rails/rails/pull/15158/files

Stack trace:

```
activesupport-4.2.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `simplified_type' for class `ActiveRecord::ConnectionAdapters::PostgreSQLColumn' (NameError)
    from activesupport-4.2.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/activerecord.rb:80:in `<class:PostgreSQLColumn>'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/activerecord.rb:74:in `<module:ConnectionAdapters>'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/activerecord.rb:70:in `<module:ActiveRecord>'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/activerecord.rb:2:in `<top (required)>'
    from activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/railties.rb:18:in `block (2 levels) in <class:Hstore>'
    from activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    from activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    from activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
    from activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
    from activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
    from activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/railties.rb:17:in `block in <class:Hstore>'
```

**Comment by diogob** [comment]
Why would you want to use this gem in Rails 4.2? Now hstore is natively supported?

**Comment by chibicode** [comment]
Sorry @diogob, my understanding was that:

- This gem added support for special `where` syntaxes like `Person.where("data ? 'foo'")` and `Person.where("data -> 'foo' = 'bar'")`
- But Rails 4 only supported using HStore via `store_accessor`, so this gem is needed to continue using queries like `Person.where("data ? 'foo'")` in Rails 4.

My mental model became this way because [the article](https://mikecoutermarsh.com/using-hstore-with-rails-4/) you mentioned on README had no examples of using query methods like `Person.where("data -> 'foo' = 'bar'")` and instead only had examples of using `store_accessor`.

But obviously my understanding was wrong. I think my misunderstanding would not have happened if [Notes about Rails 4](https://github.com/diogob/activerecord-postgres-hstore#note-about-rails-4) section described a **migration path** from `Rails 3 app using this gem -> Rails 4 app without this gem`. I think the migration path would be:

- Remove `serialize` calls
- Replace `destroy_key` and `delete_key` with something (not sure what this would be...)
- Replace `add_hstore_index` with `CREATE INDEX people_gist_data ON people USING GIST(data);` and `DROP INDEX people_gist_data`

**Comment by darrencauthon** [comment]
@chibicode I'm in a simliar spot regarding the Rails 4.1 => Rails 4.2 matter.

I've used hstore in the past with this gem, with a Hash property like "data" or something similar on my AR model.  I'd be able to write code like this:

```
thing = Thing.find params[:id]
thing.data['something_in_hstore'] # looks up to data 
```

I've heard from @diogob and others that Rails 4 has native hstore support, but when I tried to use it in my situation I hit a lot of problems.  The main issue seems to be that the Rails 4 integration is centered around ```store_accessor```, forcing me to create a property for the values I want to store on my model.  But I was using a data hash because I don't always know what data I'm going to be saving... so now I'm out of luck.  

I'm going to fiddle with some alternatives, I guess... just wanted to see if you had found any solutions in the meantime.

**Comment by bnussey** [comment]
Hey @darrencauthon I'm in a similar position as you with this one.. did you ever come up with a solution?

**Comment by darrencauthon** [comment]
I did! But... I can't remember what it was offhand. I'll look it up when I'm back at my laptop, and share. :)



—

**Comment by bnussey** [comment]
Thanks @darrencauthon that would be awesome mate, thank you

**Comment by diogob** [comment]
@darrencauthon @chibicode @bnussey It seems to me that hstore works quite transparently without any use of ```store_accessor```. At least in version 4.1. 

I just defined the following migration:
```ruby
class CreateTest < ActiveRecord::Migration
  def change
    create_table :tests do |t|
      t.hstore :data
    end
  end
end
```
and the following model:
```ruby
class Test < ActiveRecord::Base
end
```
And I was able to execute code like:
```ruby
irb(main):003:0> t = Test.new data: {a: 1, b:2}
=> #<Test id: nil, data: {"a"=>"1", "b"=>"2"}>
irb(main):004:0> t.save!
   (0.3ms)  BEGIN
  SQL (2.3ms)  INSERT INTO "tests" ("data") VALUES ($1) RETURNING "id"  [["data", "\"a\"=>\"1\",\"b\"=>\"2\""]]
   (0.5ms)  COMMIT
=> true
irb(main):005:0> t
=> #<Test id: 1, data: {"a"=>"1", "b"=>"2"}>
irb(main):006:0> t.data
=> {"a"=>"1", "b"=>"2"}
irb(main):007:0> t.data['a']
=> "1"
```

@chibicode If you are still willing to send that PR I would gladly merge it :D

BTW, have you guys looked into the json and jsonb types in PostgreSQL? They are more flexible than hstore and jsonb (only in PG 9.4+) can also take advantage of gist/gin indexes.

**Comment by darrencauthon** [comment]
@bnussey So I took a look, and @diogob is right:  The solution is to have **no** code in your AR model for the hstore column.  ActiveRecord will automatically turn it into a hash for you to use.

I was really confused, mostly because I had always had to add a line to a model these "data" properties work.  Whether it was ```serialize :data, Hash``` or the postgres hstore columns, it was my code that told the model what to do.  

Couple my assumptions to the documentation, which is/was focused on relating AR properties to hstore keys, and I couldn't see the answer right in front of me.

I think the hstore column will also be defaulted to a hash, so the functionality really stays the same when switching from this gem to Rails 4.

**Comment by bnussey** [comment]
Hey @darrencauthon and @diogob thanks for sharing, really appreciate it. @diogob mine works exactly as you said, but after I create it and then try to re-query it, I have problems and can't seem to get the value..  So for example:

`irb(main):029:0> d = Company.where(:id => 44)                                                                                                                                                          
  Company Load (0.5ms)  SELECT "companies".* FROM "companies"  WHERE "companies"."id" = 44                                                                                                             
=> #<ActiveRecord::Relation [#<Company id: 44, name: nil, average_daily_interest: nil, per_day_average_interest: {"1"=>"10", "2"=>"3"}>]>                                                                                                                  
irb(main):030:0> d.per_day_average_interest                                                                                                                                                            
NoMethodError: undefined method 'per_day_average_interest' for #<Company::ActiveRecord_Relation:0x007fa16d296dd0>                                                                                      
from /home/action/.gem/ruby/2.1.1/gems/activerecord-4.1.0/lib/active_record/relation/delegation.rb:136:in 'method_missing'                                                                     
from /home/action/.gem/ruby/2.1.1/gems/activerecord-4.1.0/lib/active_record/relation/delegation.rb:99:in 'method_missing'                                                                      
from (irb):30                                                                                                                                                                                  
from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.0/lib/rails/commands/console.rb:90:in 'start'                                                                                              
from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.0/lib/rails/commands/console.rb:9:in 'start'                                                                                               
from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:69:in 'console'                                                                                     
from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in 'run_command!'                                                                                
from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.0/lib/rails/commands.rb:17:in '<top (required)>'                                                                                           
from bin/rails:4:in 'require'                                                                                                                                                                  
from bin/rails:4:in '<main>'                                                                                                                                                                   
`                                   
Any ideas?

**Comment by darrencauthon** [comment]
@bnussey gist?

**Comment by bnussey** [comment]
Thanks for quick response @darrencauthon here it is - https://gist.github.com/bnussey/198068c89a555b5a9b99

**Comment by bnussey** [comment]
Hey @darrencauthon nevermind silly me, should have been using find or find_by not where. All working as expected. Thanks everyone.
