### ISSUE TITLE
flat-Ruby usage example request (No-Rails!) 

### ISSUE THREAD

**Issue by solyaris** [diogob/activerecord-postgres-hstore#129]
Hi Diogo & team!
Before all: thank you! This is not a real issue but a simple request:

Simple reading your README I see references to Rails  vs new Rails versions and because I'm not (?) a Rails expert I'm a bit perplex.

I'd like to use Postgres as a simple persistent layer, so yes, using  the HSTORE feature,
maybe from Sinatra or Cuba Ruby microframework, but I do not want to use Rails. Sorry.

**Question 1 (major)**
So I always loss a bit myself when I read about activereord paradigma (schema/ migrations etc.) 
Jokes a part.  May you maybe supply some readme examples about using your gem without considering Rails at all ?

**Question 2 (minor / slightly off-topic)**
Second step/info request: Me too I'm used to use activerecord ORM I confess (maybe with Sinatra too), but, generally speaking, with the main goal to use postgres as fast NOSQL DB, I ask (please note: without any malice): maybe there could be some performance improvements not using Activerecord but instead using some alternative ORM, by example Sequel ( https://github.com/jeremyevans/sequel ), or NO-ORM at all ?

Sorry for my naif questions and again: Thanks a lot for your work!
respect
giorgio

**Comment by diogob** [comment]
Hi there.
Regarding question 1, most of the examples depend only on ActiveRecord, not on rails. If you disregard the ones about Rails generators (the ones using ```rails g migration ...```) the rest you can use with Sinatra or any other framework as long as you use ActiveRecord.

Regarding the question 2, if you are experienced with PostgreSQL you definitely can squeeze more performance out of the DBMS bypassing an ORM. I would not be able to compare the perfomance of Sequel vs AR, but I can say Sequel is an amazing ORM.
