### ISSUE TITLE
Version 0.7.8

### ISSUE THREAD

**Issue by mr-dxdy** [diogob/activerecord-postgres-hstore#131]
Hi @diogob! The [Commit](https://github.com/diogob/activerecord-postgres-hstore/commit/3aed9243ddc3a976733479cb54899d00bb317257) not found in version 0.7.7 :( 
Can you publish new version 0.7.8 of gem on rubygems?

P.S.
I use rails 3.2.22...

**Comment by diogob** [comment]
Sure! Just did it, you can use the 0.7.8 now ;)

**Comment by mr-dxdy** [comment]
Thank you!
