### ISSUE TITLE
Does it work  via Rails 5?

### ISSUE THREAD

**Issue by interpegasus** [diogob/activerecord-postgres-hstore#136]
Hi,

I would like to know if the gem works with rails 5?

**Gemfile Ruby And Rails Version**
`ruby '2.3.3'
gem 'rails', '~> 5.1.4'
gem 'pg', '~> 0.9'`

**Setup**
`rails g hstore:setup
/Users/arturo/.rvm/gems/ruby-2.3.3/gems/activerecord-postgres-hstore-0.7.8/lib/activerecord-postgres-hstore/activerecord.rb:80:in `<class:PostgreSQLColumn>': undefined method `alias_method_chain' for ActiveRecord::ConnectionAdapters::PostgreSQLColumn:Class
Did you mean?  alias_method (NoMethodError)
`

**Comment by diogob** [comment]
@interpegasus why would you want to have this gem working on Rails 5? HStore has native support in Rails 5. You can also use jsonb columns in a very transparent way. Check this issue: https://github.com/diogob/activerecord-postgres-hstore/issues/127
